# enable ZMK studio


#rgb
# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y


CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y

#CONFIG_INPUT_THREAD_STACK_SIZE=4096
#CONFIG_ZMK_INPUT_PINNACLE_IDLE_SLEEPER=y
#CONFIG_ZMK_DISPLAY=y


# add support for sleep
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

#increase BT transmit power to max
#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y


