# enable ZMK studio

CONFIG_ZMK_STUDIO=y 
CONFIG_ZMK_STUDIO_LOCKING=n 
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n 


CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_OLED_WIDGET_CENTRAL_SHOW_BATTERY_PERIPHERAL_AND_CENTRAL=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_X=1

# add support for sleep
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

#increase BT transmit power to max
#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_PM_SOFT_OFF=y
